import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const TYPES_BIN = resolve(HERE, '../../bin/pasteboard-types');

const TRANSIENT_TYPES = new Set([
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  'com.apple.is-sensitive',
]);

export function readClipboard() {
  return new Promise((resolve, reject) => {
    const p = spawn('pbpaste', [], { stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '', err = '';
    p.stdout.on('data', (c) => out += c.toString('utf8'));
    p.stderr.on('data', (c) => err += c.toString('utf8'));
    p.on('error', reject);
    p.on('close', (code) =>
      code === 0 ? resolve(out) : reject(new Error(`pbpaste ${code}: ${err}`))
    );
  });
}

export function writeClipboard(text) {
  return new Promise((resolve, reject) => {
    const p = spawn('pbcopy', [], { stdio: ['pipe', 'ignore', 'pipe'] });
    p.on('error', reject);
    p.on('close', (code) =>
      code === 0 ? resolve() : reject(new Error(`pbcopy ${code}`))
    );
    p.stdin.end(text, 'utf8');
  });
}

export function isTransient() {
  const r = spawnSync(TYPES_BIN, [], { encoding: 'utf8' });
  if (r.status !== 0) return false;
  try {
    const { types } = JSON.parse(r.stdout);
    return types.some((t) => TRANSIENT_TYPES.has(t));
  } catch {
    return false;
  }
}
