use anyhow::{anyhow, Result};
use arboard::Clipboard;
use std::sync::Mutex;

static CLIPBOARD: once_cell::sync::Lazy<Mutex<Clipboard>> = once_cell::sync::Lazy::new(|| {
    Mutex::new(Clipboard::new().expect("init system clipboard"))
});

use std::path::PathBuf;

/// One snapshot of the system pasteboard, classified by payload kind.
#[derive(Debug)]
pub enum Clip {
    Empty,
    Text(String),
    Image { bytes: Vec<u8>, mime: &'static str },
    Files(Vec<PathBuf>),
}

/// Read the pasteboard's current contents into a `Clip`. Priority order
/// (macOS): PNG → TIFF → file URLs → text. On Linux: text only — image
/// and file capture are deferred to v0.7.
///
/// Returns `Clip::Empty` when the pasteboard has no recognisable content
/// or when the contents are marked transient (concealed UTI). Callers
/// MUST check `is_transient()` themselves *before* calling this fn — the
/// transient check is a precondition, not enforced here, so test code
/// can exercise the read path without a transient detour.
pub fn read_clip() -> Result<Clip> {
    #[cfg(target_os = "macos")]
    {
        if let Some(clip) = macos_pb::read_clip_macos()? {
            return Ok(clip);
        }
    }
    // Fall through to text-only path (cross-platform via arboard).
    let mut cb = CLIPBOARD.lock().map_err(|_| anyhow!("clipboard mutex poisoned"))?;
    match cb.get_text() {
        Ok(s) if !s.is_empty() => Ok(Clip::Text(s)),
        Ok(_) => Ok(Clip::Empty),
        Err(arboard::Error::ContentNotAvailable) => Ok(Clip::Empty),
        Err(e) => Err(anyhow!("clipboard read: {}", e)),
    }
}

pub fn read_clipboard() -> Result<String> {
    match read_clip()? {
        Clip::Text(s) => Ok(s),
        _ => Ok(String::new()),
    }
}

pub fn write_clipboard(text: &str) -> Result<()> {
    let mut cb = CLIPBOARD.lock().map_err(|_| anyhow!("clipboard mutex poisoned"))?;
    cb.set_text(text.to_string()).map_err(|e| anyhow!("clipboard write: {}", e))?;
    Ok(())
}

/// Returns `true` if the current pasteboard carries a "concealed" UTI
/// (org.nspasteboard.ConcealedType / AutoGeneratedType /
/// com.apple.is-sensitive). On macOS this queries NSPasteboard via
/// `objc2-app-kit`. Other platforms return `false`; CLIPBOARD_IGNORE_APPS
/// is the cross-platform compensation mechanism.
pub fn is_transient() -> bool {
    #[cfg(target_os = "macos")]
    {
        macos_pb::is_transient_macos()
    }
    #[cfg(not(target_os = "macos"))]
    {
        false
    }
}

/// Best-effort change counter for change-detection. arboard does not expose
/// the underlying changeCount; we hash-compare the text instead in the
/// watcher tick. This function exists for backward API compatibility and
/// just returns the current Unix epoch ms — the watcher does not actually
/// rely on monotonicity.
pub fn change_count() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as i64
}

#[cfg(target_os = "macos")]
mod macos_pb {
    use anyhow::Result;
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::{
        NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypePNG, NSPasteboardTypeTIFF,
    };
    use objc2_foundation::{NSString, NSURL};
    use std::path::PathBuf;

    /// Pasteboard type UTIs that signal "do not record" by community or
    /// Apple convention.
    const CONCEALED_UTIS: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
    ];

    pub fn read_clip_macos() -> Result<Option<super::Clip>> {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            let Some(types) = pb.types() else {
                return Ok::<Option<super::Clip>, anyhow::Error>(None);
            };

            // Priority 1: PNG image.
            let png_uti = unsafe { NSPasteboardTypePNG };
            if types.containsObject(png_uti) {
                if let Some(data) = pb.dataForType(png_uti) {
                    let bytes = data.to_vec();
                    return Ok(Some(super::Clip::Image {
                        bytes,
                        mime: "image/png",
                    }));
                }
            }

            // Priority 2: TIFF image (Apple-native screenshot fallback).
            let tiff_uti = unsafe { NSPasteboardTypeTIFF };
            if types.containsObject(tiff_uti) {
                if let Some(data) = pb.dataForType(tiff_uti) {
                    let bytes = data.to_vec();
                    return Ok(Some(super::Clip::Image {
                        bytes,
                        mime: "image/tiff",
                    }));
                }
            }

            // Priority 3: file URLs. Walk the per-item pasteboard so multi-file
            // selections (Finder copy of N files) come through as N entries.
            let file_uti = unsafe { NSPasteboardTypeFileURL };
            if types.containsObject(file_uti) {
                let mut paths: Vec<PathBuf> = Vec::new();
                if let Some(items) = pb.pasteboardItems() {
                    let n = items.count();
                    for i in 0..n {
                        let item = items.objectAtIndex(i);
                        if let Some(url_str) = item.stringForType(file_uti) {
                            let s = url_str.to_string();
                            // Prefer NSURL parsing (handles percent-encoding); fall
                            // back to a "file://" string-strip for malformed input.
                            let ns = NSString::from_str(&s);
                            if let Some(url) = NSURL::URLWithString(&ns) {
                                if let Some(path_str) = url.path() {
                                    paths.push(PathBuf::from(path_str.to_string()));
                                    continue;
                                }
                            }
                            if let Some(stripped) = s.strip_prefix("file://") {
                                paths.push(PathBuf::from(stripped));
                            }
                        }
                    }
                }
                if !paths.is_empty() {
                    return Ok(Some(super::Clip::Files(paths)));
                }
            }

            // No image / file types we recognise — let read_clip fall through
            // to the cross-platform text path.
            Ok(None)
        })
    }

    pub fn is_transient_macos() -> bool {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            let Some(types) = pb.types() else {
                return false;
            };
            for uti in CONCEALED_UTIS {
                let needle = NSString::from_str(uti);
                if types.containsObject(&needle) {
                    return true;
                }
            }
            false
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore] // requires real clipboard
    fn round_trip() {
        write_clipboard("hello pasteboard").unwrap();
        let got = read_clipboard().unwrap();
        assert_eq!(got, "hello pasteboard");
    }

    #[test]
    #[ignore] // requires real clipboard
    fn read_clip_returns_text_when_pasteboard_has_text() {
        write_clipboard("hello clip enum").unwrap();
        match read_clip().unwrap() {
            Clip::Text(s) => assert_eq!(s, "hello clip enum"),
            other => panic!("expected Text, got {:?}", other),
        }
    }

    #[test]
    #[cfg(not(target_os = "macos"))]
    fn is_transient_false_on_non_macos() {
        // Linux / Windows / etc. have no NSPasteboard; the fallback must be
        // false so the watcher does not silently skip every clip.
        assert!(!is_transient());
    }

    #[test]
    #[cfg(not(target_os = "macos"))]
    fn read_clip_text_or_empty_on_non_macos() {
        // On non-macOS we don't go through NSPasteboard; the read path is
        // arboard text + Empty fallback. Test only that we get a valid Clip
        // variant that's NOT Image/Files (those branches don't exist here).
        let clip = read_clip().unwrap();
        assert!(matches!(clip, Clip::Empty | Clip::Text(_)));
    }
}
