use anyhow::{anyhow, Result};
use objc2::rc::autoreleasepool;
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;

const TRANSIENT_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.apple.is-sensitive",
];

pub fn read_clipboard() -> Result<String> {
    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        // SAFETY: NSPasteboardTypeString is a valid extern static provided by AppKit.
        let s = pb
            .stringForType(unsafe { NSPasteboardTypeString })
            .ok_or_else(|| anyhow!("clipboard has no string content"))?;
        Ok(s.to_string())
    })
}

pub fn write_clipboard(text: &str) -> Result<()> {
    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        pb.clearContents();
        let s = NSString::from_str(text);
        // SAFETY: NSPasteboardTypeString is a valid extern static provided by AppKit.
        pb.setString_forType(&s, unsafe { NSPasteboardTypeString });
        Ok(())
    })
}

pub fn is_transient() -> bool {
    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        let Some(types) = pb.types() else {
            return false;
        };
        for ty in types.iter() {
            let s = ty.to_string();
            if TRANSIENT_TYPES.contains(&s.as_str()) {
                return true;
            }
        }
        false
    })
}

pub fn change_count() -> i64 {
    autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount() as i64)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore] // requires real clipboard
    fn round_trip() {
        write_clipboard("hello pasteboard").unwrap();
        let got = read_clipboard().unwrap();
        assert_eq!(got, "hello pasteboard");
    }
}
