use anyhow::{anyhow, Result};
use arboard::Clipboard;
use std::sync::Mutex;

static CLIPBOARD: once_cell::sync::Lazy<Mutex<Clipboard>> = once_cell::sync::Lazy::new(|| {
    Mutex::new(Clipboard::new().expect("init system clipboard"))
});

use std::path::PathBuf;

/// One snapshot of the system pasteboard, classified by payload kind.
#[derive(Debug)]
pub enum Clip {
    Empty,
    Text(String),
    Image { bytes: Vec<u8>, mime: &'static str },
    Files(Vec<PathBuf>),
}

/// Read the pasteboard's current contents into a `Clip`. Priority order
/// (macOS): PNG → TIFF → file URLs → text. On Linux: text only — image
/// and file capture are deferred to v0.7.
///
/// Returns `Clip::Empty` when the pasteboard has no recognisable content
/// or when the contents are marked transient (concealed UTI). Callers
/// MUST check `is_transient()` themselves *before* calling this fn — the
/// transient check is a precondition, not enforced here, so test code
/// can exercise the read path without a transient detour.
pub fn read_clip() -> Result<Clip> {
    #[cfg(target_os = "macos")]
    {
        if let Some(clip) = macos_pb::read_clip_macos()? {
            return Ok(clip);
        }
    }
    // Fall through to text-only path (cross-platform via arboard).
    let mut cb = CLIPBOARD.lock().map_err(|_| anyhow!("clipboard mutex poisoned"))?;
    match cb.get_text() {
        Ok(s) if !s.is_empty() => Ok(Clip::Text(s)),
        Ok(_) => Ok(Clip::Empty),
        Err(arboard::Error::ContentNotAvailable) => Ok(Clip::Empty),
        Err(e) => Err(anyhow!("clipboard read: {}", e)),
    }
}

pub fn read_clipboard() -> Result<String> {
    match read_clip()? {
        Clip::Text(s) => Ok(s),
        _ => Ok(String::new()),
    }
}

pub fn write_clipboard(text: &str) -> Result<()> {
    let mut cb = CLIPBOARD.lock().map_err(|_| anyhow!("clipboard mutex poisoned"))?;
    cb.set_text(text.to_string()).map_err(|e| anyhow!("clipboard write: {}", e))?;
    Ok(())
}

/// Returns `true` if the current pasteboard carries a "concealed" UTI
/// (org.nspasteboard.ConcealedType / AutoGeneratedType /
/// com.apple.is-sensitive). On macOS this queries NSPasteboard via
/// `objc2-app-kit`. Other platforms return `false`; CLIPBOARD_IGNORE_APPS
/// is the cross-platform compensation mechanism.
pub fn is_transient() -> bool {
    #[cfg(target_os = "macos")]
    {
        macos_pb::is_transient_macos()
    }
    #[cfg(not(target_os = "macos"))]
    {
        false
    }
}

/// Best-effort change counter for change-detection. arboard does not expose
/// the underlying changeCount; we hash-compare the text instead in the
/// watcher tick. This function exists for backward API compatibility and
/// just returns the current Unix epoch ms — the watcher does not actually
/// rely on monotonicity.
pub fn change_count() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as i64
}

#[cfg(target_os = "macos")]
mod macos_pb {
    use anyhow::Result;
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::NSPasteboard;
    use objc2_foundation::NSString;

    /// Pasteboard type UTIs that signal "do not record" by community or
    /// Apple convention.
    const CONCEALED_UTIS: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
    ];

    pub fn read_clip_macos() -> Result<Option<super::Clip>> {
        // Stub: image + file branches land in T2 Task 5.
        Ok(None)
    }

    pub fn is_transient_macos() -> bool {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            let Some(types) = pb.types() else {
                return false;
            };
            for uti in CONCEALED_UTIS {
                let needle = NSString::from_str(uti);
                if types.containsObject(&needle) {
                    return true;
                }
            }
            false
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore] // requires real clipboard
    fn round_trip() {
        write_clipboard("hello pasteboard").unwrap();
        let got = read_clipboard().unwrap();
        assert_eq!(got, "hello pasteboard");
    }

    #[test]
    #[ignore] // requires real clipboard
    fn read_clip_returns_text_when_pasteboard_has_text() {
        write_clipboard("hello clip enum").unwrap();
        match read_clip().unwrap() {
            Clip::Text(s) => assert_eq!(s, "hello clip enum"),
            other => panic!("expected Text, got {:?}", other),
        }
    }

    #[test]
    #[cfg(not(target_os = "macos"))]
    fn is_transient_false_on_non_macos() {
        // Linux / Windows / etc. have no NSPasteboard; the fallback must be
        // false so the watcher does not silently skip every clip.
        assert!(!is_transient());
    }
}
